---
title: "ComparingAirportERA5Temps"
author: "Amaryllis Adey"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading in the ERA5 data

```{r}
ERA_CRD <- read.csv("DataFiles/ERA5_Cordova.csv", header=TRUE)

ERA_CRD <- ERA_CRD %>%
  rename(temp = "t2m")

ERA_YF <- read.csv("DataFiles/ERA5_Yakutat.csv", header=TRUE)

ERA_YF <- ERA_YF %>%
  rename(temp = "t2m")

```

## Loading in the Airport data

```{r}
airport <- read.csv("DataFiles/AirportTemps.csv", header = TRUE)

Airport_CRD <- airport %>%
  filter(NAME == "CORDOVA AIRPORT")

Airport_YF <- airport %>%
  filter(NAME == "YAKUTAT AIRPORT")
```


## Need to change the ERA data to daily means to make them comparable to the airport data

```{r}
ERA_CRD

ERA_CRD_test <- ERA_CRD %>%
  group_by(Year, Month, day) %>%
  summarize(mean_temp = mean(temp, na.rm = TRUE)) %>%
  ungroup()

ERA_CRD_test <- ERA_CRD_test %>%
  mutate(date = as.Date(paste(Year, Month, day, sep = "-")))

ERA_CRD <- ERA_CRD_test
  
ERA_YF

ERA_YF_test <- ERA_YF %>%
  group_by(Year, Month, day) %>%
  summarize(mean_temp = mean(temp, na.rm = TRUE)) %>%
  ungroup()

ERA_YF_test <- ERA_YF_test %>%
  mutate(date = as.Date(paste(Year, Month, day, sep = "-")))
  
ERA_YF <- ERA_YF_test

```

## Group the ERA5 data with the airport data for both regions

```{r}
# Convert 'DATE' in Airport_CRD to Date format
Airport_CRD <- Airport_CRD %>%
  mutate(DATE = as.Date(DATE))

# Merge ERA_CRD and Airport_CRD based on 'date' and 'DATE'
merged_CRD <- inner_join(ERA_CRD, Airport_CRD, by = c("date" = "DATE")) %>%
  select(ERA5Temp = mean_temp, AirportTemp = TAVG2, date)

# View the first few rows of merged dataframe
head(merged_CRD)

# Convert 'DATE' in Airport_CRD to Date format
Airport_YF <- Airport_YF %>%
  mutate(DATE = as.Date(DATE))

# Merge ERA_CRD and Airport_CRD based on 'date' and 'DATE'
merged_YF <- inner_join(ERA_YF, Airport_YF, by = c("date" = "DATE")) %>%
  select(ERA5Temp = mean_temp, AirportTemp = TAVG2, date)

# View the first few rows of merged dataframe
head(merged_YF)
```

## Plot the temperatures for the CRD and YF

```{r}
# CRD
merged_CRD

CRD_TempComps <- ggplot(data = merged_CRD, aes(x = date)) +
  geom_line(aes(y = ERA5Temp, color = "ERA5Temp")) +  # Specify color as "ERA5Temp" for legend
  geom_line(aes(y = AirportTemp, color = "AirportTemp")) +  # Specify color as "AirportTemp" for legend
  labs(
    x = "Date",  # X-axis label
    y = "Temperature (C)",  # Y-axis label
    color = "Temperature Data"  # Legend title
  ) +
  scale_color_manual(
    name = "Temperature Data",  # Rename the legend title
    values = c("ERA5Temp" = "blue", "AirportTemp" = "red"),  # Assign colors and labels
    labels = c("Airport Temp", "ERA5 Temp")  # Specify legend labels
  ) +
  theme_bw() +
  ggtitle("Copper River Delta")

ggsave("Plots/CRD_TempComps.png", plot = CRD_TempComps, width = 8, height = 6)

# CRD
merged_YF

YF_TempComps <- ggplot(data = merged_YF, aes(x = date)) +
  geom_line(aes(y = ERA5Temp, color = "ERA5Temp")) +  # Specify color as "ERA5Temp" for legend
  geom_line(aes(y = AirportTemp, color = "AirportTemp")) +  # Specify color as "AirportTemp" for legend
  labs(
    x = "Date",  # X-axis label
    y = "Temperature (C)",  # Y-axis label
    color = "Temperature Data"  # Legend title
  ) +
  scale_color_manual(
    name = "Temperature Data",  # Rename the legend title
    values = c("ERA5Temp" = "blue", "AirportTemp" = "red"),  # Assign colors and labels
    labels = c("Airport Temp", "ERA5 Temp")  # Specify legend labels
  ) +
  theme_bw() +
  ggtitle("Yakutat Forelands")

ggsave("Plots/YF_TempComps.png", plot = YF_TempComps, width = 8, height = 6)

```

